name: Weekly Report
on:
  schedule:
    - cron: '45 04 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/activity-report@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
